name: cicd test project CI 
on:
  push:
    branches:[master]
  pull_request:
    branches:[master]
jobs:
  build:
    runs-on:ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 20
        uses: actions/setup-node@v2
        with:
          node_version:'20'
      - run: npm install
      - run: npm run build -- prefix client